version: "1.0"

device:
  id: "C1"
  name: "T2.MICRO"

edge-feed:
  cloud-rabbitmq:
    mode: "messaging"
    protocol: "amqp"
    host: "mqserver-01.technipun.com"
    port: "5672"
    user: "edge-user"
    password: "M4cQJb8eB6FP"
    queue: "data"
    dataratereadseconds: 10

remote-commander:
  main:
    mode: "messaging"
    protocol: "amqp"
    host: "mqserver-01.technipun.com"
    port: "5672"
    user: "edge-user"
    password: "M4cQJb8eB6FP"
    channel: "command-e1"

monitoring-manager:
  main:
    mode: "messaging"
    protocol: "amqp"
    host: "mqserver-01.technipun.com"
    port: "5672"
    user: "edge-user"
    password: "M4cQJb8eB6FP"
    channel: "system-stats-e1"

